// src/components/Artifact/views/ArtifactDetailCard.vue
<script setup lang="ts">
import { Lock } from '@/components/Tags';
import BasicDetailCard from '@/components/DetailCard/index.vue';
import { ClassNameFactor } from '@/utils/className';
import { type ArtifactSlot } from '../interfaces';
import Describe from './ArtifactDescribe.vue';
import { GetArtifactTypeChinese, ArtifactEffectSearch } from '../functions';

import { reactive, toRefs, watch } from 'vue';
import { merge } from '@/utils';

interface ArtifactDetailCardProps {
  id: number;
  type: ArtifactSlot;
  lock: boolean;
  suitCount: 0 | 1 | 2 | 3 | 4 | 5;
  lvl: number;
  main: {
    key: string;
    value: string;
    [key: string]: any;
  };
  sub?: {
    key: string;
    value: string;
    [key: string]: any;
  };
  subs: {
    key: string;
    value: string;
    [key: string]: any;
  }[];
}

const props = defineProps<ArtifactDetailCardProps>();

const { sub, main, subs, type, suitCount } = toRefs(props);

const S = ClassNameFactor('artifact-detail-card-');

const data = reactive(ArtifactEffectSearch(props.id));

watch(
  () => props.id,
  () => {
    merge(data, ArtifactEffectSearch(props.id));
  }
);
</script>

<template>
  <BasicDetailCard
    :title="data.slots[props.type]!.name"
    :rarity="data.rarity"
    :sub="sub"
    :main="main"
    :imgurl="data.slots[props.type]!.imgUrl"
    :type="GetArtifactTypeChinese(type)"
  >
    <div :class="S('describe')">
      <div :class="S('lvl-container')">
        <div :class="S('lvl')">+{{ props.lvl }}</div>
        <Lock
          :size="30"
          :lock="props.lock"
        />
      </div>
      <div :class="S('attributes')">
        <div
          v-for="i in subs"
          :key="i.key + i.value"
        >
          {{ ' · ' }}
          {{ i.key }}+{{ i.value }}
        </div>
      </div>
      <Describe
        :class="S('effect-describe')"
        :id="props.id"
        :active="suitCount"
      />
      <div :class="S('txt-describe')">{{ data.slots[props.type]!.describe }}</div>
    </div>
  </BasicDetailCard>
</template>

<style scoped lang="less">
.artifact-detail-card {
  &-attributes > div {
    color: @fontdarkgray;
    font-size: 22px;
    margin: 4px 0;
  }

  &-effect-describe {
    font-size: 22px;
    margin-top: 15px;
  }

  &-txt-describe {
    margin-top: 10px;
    font-size: 22px;
    color: @fontlightgray;
  }

  &-lvl {
    &-container {
      display: flex;
      justify-content: space-between;
      align-items: center;

      height: 50px;
    }
    display: inline-block;
    // margin: 0 10px;
    padding: 0 10px;
    border-radius: 3px;
    background-color: @shadow;
    font-size: 18px;

    color: @blank-white;
  }
}
</style>

// src/components/Artifact/views/ArtifactDetailCard/index.tsx
import { Lock, Enable } from '@/components/Tags';
import { BasicDetailCard, BasicDetailCardProps } from '@/components/DetailCard';
import { ClassNameWithCSSModuleFactor } from '@/utils/className';
import {
  ArtifactInstanceModel,
  ArtifactSlot,
  ArtifactSuitModel,
} from '../../interfaces';

import { useEffect, useState } from 'react';
import { GetArtifactSlot, GetArtifactTypeChinese } from '../../functions';
import ArtifactStyle from './index.less';

interface ArtifactDetailCardProps extends BasicDetailCardProps {
  id: number;
  artifact: ArtifactSuitModel;
  type: ArtifactSlot;
  lock: boolean;
  suitCount: 0 | 1 | 2 | 3 | 4 | 5;
  lvl: number;
  subs: {
    key: string;
    value: string;
    [key: string]: any;
  }[];
}

const ArtifactDetailCard = (props: ArtifactDetailCardProps) => {
  const prefix = 'artifact-detail-card-';
  const { id, subs, artifact, type, suitCount } = props;

  const [slot, setSlot] = useState({ name: '', imgUrl: '', describe: '' } as {
    name: string;
    imgUrl: string;
    describe: string;
  });

  const Style = ClassNameWithCSSModuleFactor(ArtifactStyle, prefix);

  useEffect(() => {
    setSlot(GetArtifactSlot(artifact, type));
  }, []);

  return (
    <BasicDetailCard
      {...props}
      imgUrl={slot.imgUrl}
      title={slot.name}
      type={GetArtifactTypeChinese(type)}
    >
      <div className={Style(['describe'])}>
        <div className={Style(['lvl-container'])}>
          <div className={Style(['lvl'])}>+{props.lvl}</div>
          <Lock size={30} lock={props.lock} />
        </div>
        <div className={Style(['attributes'])}>
          {subs.map((i) => (
            <div key={i.key + i.value}>
              {' · '}
              {i.key}+{i.value}
            </div>
          ))}
        </div>
        <div className={Style(['describe-enable'])}>{artifact.name}:</div>
        <div className={Style(['effect-box'])}>
          {artifact.effects.map((i) => (
            <div key={i.limit} style={{ overflow: 'hidden' }}>
              <Enable
                size={20}
                enable={i.limit <= suitCount}
                style={{ float: 'left' }}
              />
              <div
                className={Style({
                  'describe-enable': i.limit <= suitCount,
                  effect: true,
                })}
              >
                {i.limit}件套：{i.describe}
              </div>
            </div>
          ))}
        </div>
        <div>{slot.describe}</div>
      </div>
    </BasicDetailCard>
  );
};

export { ArtifactDetailCardProps };
export { ArtifactDetailCard };
